name: Python Code Formatting Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: YAPF Python Code Formatting Check
      # You may pin to the exact commit or the version.
      # uses: AlexanderMelde/yapf-action@a2053dba9adceb173b38e58acaad7436a1934bdd
      uses: AlexanderMelde/yapf-action@v1.0
